//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My2Cents.HTC.AHPilotStats.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My2Cents.HTC.AHPilotStats.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AKUAG2 {
            get {
                object obj = ResourceManager.GetObject("AKUAG2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Spatula1 {
            get {
                object obj = ResourceManager.GetObject("Spatula1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red255\green0\blue0;\red0\green0\blue0;}
        ///{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\qc\cf1\b\f0\fs22 Help a Spatula\par
        ///\pard\cf2\b0\fs20\par
        ///This application has been lovingly conceived, created, maintained by Spatula in his very limited spare time. Literally hundreds of hours has gone into this application so you can quantify any pilots in-game peformance. \par
        ///\par
        ///This application continues  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tip0 {
            get {
                return ResourceManager.GetString("Tip0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red255\green0\blue0;\red0\green0\blue0;}
        ///{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\qc\cf1\b\f0\fs22 Grid Column Filters\fs24\par
        ///\pard\cf2\b0\fs20\par
        ///Did you know you can right click on most grid column headers to define a custom filter for that column? You can define one filter per column for as many columns in the grid as you like. This is very useful for homing in on subsets of data within th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tip1 {
            get {
                return ResourceManager.GetString("Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red255\green0\blue0;\red0\green0\blue0;}
        ///{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\qc\cf1\b\f0\fs22 Performance\fs20\par
        ///\b0\par
        ///\pard\cf2 The scores loader deliberately pauses a few seconds between loading multiple scores in order to save load on Hitech Creations web servers. While this adds more delay than technically necessary, you will still get your scores, and know that you are not causing  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tip2 {
            get {
                return ResourceManager.GetString("Tip2", resourceCulture);
            }
        }
    }
}
