//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
namespace My2Cents.HTC.PilotScoreSvc.Types
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class AcesHighPilotScore {
        
        /// <remarks/>
        public string GameId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TourId;
        
        /// <remarks/>
        public string TourDetails;
        
        /// <remarks/>
        public string TourType;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemy VsEnemy;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjects VsObjects;
        
        /// <remarks/>
        public AcesHighPilotScoreOverall Overall;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemy {
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyFighter Fighter;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyAttack Attack;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyVehicleBoat VehicleBoat;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyFighter {
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyFighterKillToDeathPlus1 KillToDeathPlus1;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyFighterKillPerSortie KillPerSortie;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyFighterKillPerHour KillPerHour;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyFighterHitPercentage HitPercentage;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyFighterPoints Points;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyFighterKillToDeathPlus1 {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreOverallTotal {
        
        /// <remarks/>
        public int Kills;
        
        /// <remarks/>
        public int Assists;
        
        /// <remarks/>
        public int Sorties;
        
        /// <remarks/>
        public int Landed;
        
        /// <remarks/>
        public int Bailed;
        
        /// <remarks/>
        public int Ditched;
        
        /// <remarks/>
        public int Captured;
        
        /// <remarks/>
        public int Death;
        
        /// <remarks/>
        public int Disco;
        
        /// <remarks/>
        public int Time;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreOverallVehicleBoat {
        
        /// <remarks/>
        public int Kills;
        
        /// <remarks/>
        public int Assists;
        
        /// <remarks/>
        public int Sorties;
        
        /// <remarks/>
        public int Landed;
        
        /// <remarks/>
        public int Bailed;
        
        /// <remarks/>
        public int Ditched;
        
        /// <remarks/>
        public int Captured;
        
        /// <remarks/>
        public int Death;
        
        /// <remarks/>
        public int Disco;
        
        /// <remarks/>
        public int Time;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreOverallAttack {
        
        /// <remarks/>
        public int Kills;
        
        /// <remarks/>
        public int Assists;
        
        /// <remarks/>
        public int Sorties;
        
        /// <remarks/>
        public int Landed;
        
        /// <remarks/>
        public int Bailed;
        
        /// <remarks/>
        public int Ditched;
        
        /// <remarks/>
        public int Captured;
        
        /// <remarks/>
        public int Death;
        
        /// <remarks/>
        public int Disco;
        
        /// <remarks/>
        public int Time;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreOverallBomber {
        
        /// <remarks/>
        public int Kills;
        
        /// <remarks/>
        public int Assists;
        
        /// <remarks/>
        public int Sorties;
        
        /// <remarks/>
        public int Landed;
        
        /// <remarks/>
        public int Bailed;
        
        /// <remarks/>
        public int Ditched;
        
        /// <remarks/>
        public int Captured;
        
        /// <remarks/>
        public int Death;
        
        /// <remarks/>
        public int Disco;
        
        /// <remarks/>
        public int Time;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreOverallFighter {
        
        /// <remarks/>
        public int Kills;
        
        /// <remarks/>
        public int Assists;
        
        /// <remarks/>
        public int Sorties;
        
        /// <remarks/>
        public int Landed;
        
        /// <remarks/>
        public int Bailed;
        
        /// <remarks/>
        public int Ditched;
        
        /// <remarks/>
        public int Captured;
        
        /// <remarks/>
        public int Death;
        
        /// <remarks/>
        public int Disco;
        
        /// <remarks/>
        public int Time;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreOverall {
        
        /// <remarks/>
        public AcesHighPilotScoreOverallFighter Fighter;
        
        /// <remarks/>
        public AcesHighPilotScoreOverallBomber Bomber;
        
        /// <remarks/>
        public AcesHighPilotScoreOverallAttack Attack;
        
        /// <remarks/>
        public AcesHighPilotScoreOverallVehicleBoat VehicleBoat;
        
        /// <remarks/>
        public AcesHighPilotScoreOverallTotal Total;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsVehicleBoatFieldCaptures {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsVehicleBoatPoints {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsVehicleBoatHitPercentage {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsVehicleBoatDamagePerSortie {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsVehicleBoatDamagePerDeathPlus1 {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsVehicleBoat {
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsVehicleBoatDamagePerDeathPlus1 DamagePerDeathPlus1;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsVehicleBoatDamagePerSortie DamagePerSortie;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsVehicleBoatHitPercentage HitPercentage;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsVehicleBoatPoints Points;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsVehicleBoatFieldCaptures FieldCaptures;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsAttackFieldCaptures {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsAttackPoints {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsAttackHitPercentage {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsAttackDamagePerSortie {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsAttackDamagePerDeathPlus1 {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsAttack {
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsAttackDamagePerDeathPlus1 DamagePerDeathPlus1;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsAttackDamagePerSortie DamagePerSortie;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsAttackHitPercentage HitPercentage;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsAttackPoints Points;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsAttackFieldCaptures FieldCaptures;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsBomberFieldCaptures {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsBomberPoints {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsBomberHitPercentage {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsBomberDamagePerSortie {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsBomberDamagePerDeathPlus1 {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjectsBomber {
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsBomberDamagePerDeathPlus1 DamagePerDeathPlus1;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsBomberDamagePerSortie DamagePerSortie;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsBomberHitPercentage HitPercentage;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsBomberPoints Points;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsBomberFieldCaptures FieldCaptures;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsObjects {
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsBomber Bomber;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsAttack Attack;
        
        /// <remarks/>
        public AcesHighPilotScoreVsObjectsVehicleBoat VehicleBoat;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyVehicleBoatPoints {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyVehicleBoatHitPercentage {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyVehicleBoatKillPerHour {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyVehicleBoatKillPerSortie {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyVehicleBoatKillToDeathPlus1 {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyVehicleBoat {
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyVehicleBoatKillToDeathPlus1 KillToDeathPlus1;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyVehicleBoatKillPerSortie KillPerSortie;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyVehicleBoatKillPerHour KillPerHour;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyVehicleBoatHitPercentage HitPercentage;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyVehicleBoatPoints Points;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyAttackPoints {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyAttackHitPercentage {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyAttackKillPerHour {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyAttackKillPerSortie {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyAttackKillToDeathPlus1 {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyAttack {
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyAttackKillToDeathPlus1 KillToDeathPlus1;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyAttackKillPerSortie KillPerSortie;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyAttackKillPerHour KillPerHour;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyAttackHitPercentage HitPercentage;
        
        /// <remarks/>
        public AcesHighPilotScoreVsEnemyAttackPoints Points;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyFighterPoints {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyFighterHitPercentage {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyFighterKillPerHour {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
    
    /// <remarks/>
    public class AcesHighPilotScoreVsEnemyFighterKillPerSortie {
        
        /// <remarks/>
        public System.Decimal Score;
        
        /// <remarks/>
        public int Rank;
    }
}
