//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
namespace My2Cents.HTC.PilotScoreSvc.Types
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class AcesHighPilotStats {
        
        /// <remarks/>
        public string GameId;
        
        /// <remarks/>
        public string TourId;
        
        /// <remarks/>
        public string TourDetails;
        
        /// <remarks/>
        public string TourType;
        
        /// <remarks/>
        public AcesHighPilotStatsVsObjects VsObjects;
        
        /// <remarks/>
        public AcesHighPilotStatsVsCountry VsCountry;
    }
    
    /// <remarks/>
    public class AcesHighPilotStatsVsObjects {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectScore")]
        public ObjectScore[] ObjectScore;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class ObjectScore {
        
        /// <remarks/>
        public string Model;
        
        /// <remarks/>
        public int KillsIn;
        
        /// <remarks/>
        public int KillsOf;
        
        /// <remarks/>
        public int KilledBy;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public int? DiedIn;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class CountryScore {
        
        /// <remarks/>
        public string Country;
        
        /// <remarks/>
        public int KillsAs;
        
        /// <remarks/>
        public int KillsOf;
        
        /// <remarks/>
        public int KilledBy;
    }
    
    /// <remarks/>
    public class AcesHighPilotStatsVsCountry {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CountryScore")]
        public CountryScore[] CountryScore;
    }
}
